### ISSUE TITLE
How to turn off evil mode

### ISSUE THREAD

**Issue by johnbendi** [skeeto/.emacs.d#9]
I'm more than happy using the little arrow keys on the lower right of my laptop keyboard for navigation and together with `ctrl` keys for jumping between windows. I have never liked vim style editing. I have tried it but it doesn't give me the freedom I need.  

Also I need some help with adjusting the font as it looks very small on my hiDpi laptop. 

To be honest a lot of things have changed since I last cloned your repo that I am not too comfortable with. 

I just mostly like the turning off of tabs and menus

Thanks for putting effort into this project!

**Comment by johnbendi** [comment]
![Screenshot from 2019-10-08 09-07-50](https://user-images.githubusercontent.com/1025834/66378343-2753e600-e9ab-11e9-94d5-28f0ea72ed8a.png)

As you can see my setup is not primed for evil mode.

**Comment by johnbendi** [comment]
I figured the best way to remove the feature is to comment out the corresponding `use-package` form in `init.el`.

Or do you think there is a better way?

**Comment by skeeto** [comment]
Once Emacs is started you can turn it off completely with M-x evil-mode. 
I think removing its use-package form, like you said, should work, but 
only if you also remove the evil-smartparens use-package form. I'm not 
spotting any other dependencies on Evil outside of that.

My configuration isn't intended to be a "starter configuration," and I 
break things from time to time without considering who else might be 
using it. I keep my personal configuration online because 1) it's super 
convenient for me and 2) I want to share my own tricks and discoveries 
with the broader Emacs community.

So you should consider starting your Emacs configuration completely from 
scratch, adding specific things from my (and others') configuration only 
after you fully understand how they work. You probably don't even need 
some 75% of my configuration anyway, and most of it certainly isn't 
discoverable without reading the code. If you like my gpkg solution to 
packaging, then copy that, along with the Makefile, and keep using it. 
Remove packages you don't want, add new packages you want to use. I 
consider my configuration in the public domain (UNLICENSE), so there's 
zero friction in using whatever you like.

**Comment by johnbendi** [comment]
Thanks a lot @skeeto. I did just that. I started my own based on your template. One thing I particularly like is how your setup has evolved over the years to be quite modular. Especially with your use of `gpkg`, `use-package` and `Makefile`.

**Comment by johnbendi** [comment]
I think it's safe to close this issue now. Thanks.
